# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06ebd37eef1efc7bb54258152e40af3e4cb5dd6c1c765c7649bb43197acd0ddc5686603c5c3a1be88c370b15b5f4fa3cce926fbe4ef1e37978deaae0e831465b

test:
  secret_key_base: 71bd0993a76b57b96ddcb5d87d8f059bd1af0a378cf9a229df85f518846c781ed49808d7f148b37640365148ff75676856aa18487a1075c7432f704cb4aec0e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
